version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bugtracker
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  python_service:
    build:
      context: .
      dockerfile: docker/python.Dockerfile
    ports:
      - "8000:8000"

volumes:
  mongo-data: