services:
  - type: web
    name: bugtracker-api
    env: node
    plan: free
    buildCommand: cd server/api && npm install
    startCommand: node app.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://igobymatthew:*****@bugtracker-cluster.xxxxx.mongodb.net/bugtracker?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: *****
    autoDeploy: true
    region: oregon

  - type: web
    name: bugtracker-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    redirects:
      - source: /.*         # all paths
        destination: /index.html
        statusCode: 200     # force SPA fallback
    autoDeploy: true