services:
  - type: web
    name: bugtracker-api
    env: node
    plan: free
    buildCommand: cd server/api && npm install
    startCommand: node app.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://igobymatthew:18LC8UOK4sFeHREf@bugtracker-cluster.xxxxx.mongodb.net/bugtracker?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: BugAppJWT987!
    autoDeploy: true
    region: oregon

  - type: web
    name: bugtracker-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    autoDeploy: true
